### 1. Setup & Data Loading

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Display settings
pd.set_option('display.max_columns', 50)
pd.set_option('display.float_format', lambda x: f'{x:.3f}')
plt.rcParams['figure.figsize'] = (12, 5)
plt.rcParams['axes.spines.top']   = False
plt.rcParams['axes.spines.right'] = False
sns.set_style('whitegrid')

RANDOM_STATE = 42
print('Libraries loaded successfully.')

Libraries loaded successfully.

In [4]:
train = pd.read_csv(r'C:\projects\Hackathon\kaggle-playground-irrigation-prediction\data\train.csv')
test = pd.read_csv(r'C:\projects\Hackathon\kaggle-playground-irrigation-prediction\data\test.csv')
sample_submission = pd.read_csv(r'C:\projects\Hackathon\kaggle-playground-irrigation-prediction\data\sample_submission.csv')

df = train.copy(deep = True)
df_test = test.copy(deep = True)

print(f'Train shape :  {train.shape}')
print(f'Test shape :  {test.shape}')

Train shape :  (630000, 21)
Test shape :  (270000, 20)

In [5]:
df.sample(3)

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
189630,189630,Silt,6.610,63.220,0.410,0.970,39.770,85.960,727.100,6.750,18.700,Sugarcane,Sowing,Kharif,Drip,River,9.110,No,75.640,Central,Low
32928,32928,Sandy,5.160,33.720,0.380,3.380,17.800,33.680,1262.500,4.270,11.220,Potato,Sowing,Rabi,Drip,Groundwater,7.080,No,40.730,East,Low
96476,96476,Loamy,7.630,32.470,1.390,1.820,30.850,40.090,1231.810,5.540,11.730,Maize,Vegetative,Zaid,Drip,River,3.530,No,5.060,North,Medium

### 2. Data Quality Check

In [6]:
def quick_eda(df):
    
    print('=' * 55)
    print(f'  Shape      : {df.shape[0]:,} rows x {df.shape[1]} columns')
    print(f'  Duplicates : {df.duplicated().sum()}')
    print(f'  Memory     : {df.memory_usage(deep=True).sum() / 1e6:.1f} MB')
    print('=' * 55)

    info = pd.DataFrame({
        'dtype'    : df.dtypes,
        'non-null' : df.count(),
        'missing'  : df.isnull().sum(),
        'missing%' : (df.isnull().mean() * 100).round(2),
        'unique'   : df.nunique()
    })
    return info

quick_eda(df)

=======================================================
  Shape      : 630,000 rows x 21 columns
  Duplicates : 0
  Memory     : 369.5 MB
=======================================================

                           dtype  non-null  missing  missing%  unique
id                         int64    630000        0     0.000  630000
Soil_Type                    str    630000        0     0.000       4
Soil_pH                  float64    630000        0     0.000     341
Soil_Moisture            float64    630000        0     0.000    5223
Organic_Carbon           float64    630000        0     0.000     131
Electrical_Conductivity  float64    630000        0     0.000     341
Temperature_C            float64    630000        0     0.000    2934
Humidity                 float64    630000        0     0.000    6475
Rainfall_mm              float64    630000        0     0.000   19308
Sunlight_Hours           float64    630000        0     0.000     701
Wind_Speed_kmh           float64    630000        0     0.000    1935
Crop_Type                    str    630000        0     0.000       6
Crop_Growth_Stage            str    630000        0     0.000       4
Season                       str    630000        0     0.000       3
Irrigation_Type              str    630000        0     0.000       4
Water_Source                 str    630000        0     0.000       4
Field_Area_hectare       float64    630000        0     0.000    1466
Mulching_Used                str    630000        0     0.000       2
Previous_Irrigation_mm   float64    630000        0     0.000   10110
Region                       str    630000        0     0.000       5
Irrigation_Need              str    630000        0     0.000       3